### ISSUE TITLE
圈速榜建议

### ISSUE THREAD

**Issue by w9315273** [Phil-Libra/kbracer-goldenport#1]
建议给圈速马力这类参数 后面加上单位 或者是表头随动 不然数据多了后 往下一拉 一时间不知道那些数值是什么 不太容易浏览

**Comment by Phil-Libra** [comment]
> 建议给圈速马力这类参数 后面加上单位 或者是表头随动 不然数据多了后 往下一拉 一时间不知道那些数值是什么 不太容易浏览

固定表头是支持的，只是某些浏览器（主要是苹果的设备）会出现bug，所以暂时没开启。
表格数据不考虑加单位了，一是显得混乱和拥挤，二是万一以后需要对数据进行排序之类，加了单位就不方便。
